# -*- coding: utf-8 -*-
'''
Created on 21.08.2013

@author: alexander.kozlov@itseez.com
'''

LanguageMap = {'rus' : 0, 'eng' : 1}

Dictionary = {
              'loginForm': {
                          'title' : ['Вход', 'Login'],
                          'loginlabel': ['Имя пользователя', 'User name'],
                          'passwordlabel': ['Пароль', 'Password'],
                          'sendbutton': ['Войти', 'Login'],
                          'loginError' : ['Неверное имя пользователя или пароль!', 'Incorrect login or password!'],
                          },
              
              'settingsForm' : {
                          'title' : ['Настройки', 'Settings'],
                          'shoppanellabel' : ['Магазин', 'Shop'],
                          'shopidlabel' : ['Идентификатор магазина', 'Shop unique id'],
                          'schedulelabel' : ['Время суток, в которое происходит подсчет людей', 'Counting period'],
                          'alldaylabel' : ['круглосуточно', 'All day'],
                          'countfromlabel' : ['От', 'From'],
                          'counttilllabel' : ['До', 'To'],
                          'reportsendinglabel' : ['Настройка отчетов', 'Report sending'],
                          'reportRangeLabel' : ['Частота создания отчетов в часах', 'Send report every (hours)'],
                          'manualHoursLabel' : ['Указать моменты создания отчетов (формат - ЧЧ:ММ,ЧЧ:ММ)', 'Set time points manually (format is HH:MM,HH:MM)'],
                          'is1Clabel' : ['Отправлять отчеты в формате 1С', 'Send 1C reports'],
                          'deliveryTypesLabel' : ['Способы доставки', 'Report delivery types'],
                          'sendByEmailLabel' : ['Отправлять по почте', 'Send reports by email'],
                          'toEmailLabel' : ['Кому', 'To'],
                          'sendToServerLabel' : ['Отправлять на сервер' , 'Send to server'],
                          'serverAddressLabel' : ['Адрес', 'Address'],
                          'serverPortLabel' : ['Порт', 'Port'],
                          'sharedFolderLabel' : ['Копировать отчеты в папку', 'Copy reports to shared folder:'],
                          'sharePathLabel' : ['Путь', 'Path'],
                          'shareUserLabel' : ['Пользователь', 'User'],
                          'sharePasswordLabel' : ['Пароль', 'Password'],
                          'outgoingEmailLabel' : ['Настройки электронной почты', 'Outgoing email settings'],
                          'emailFromLabel' : ['От кого', 'From'],
                          'smtpServerLabel' : ['SMTP сервер', 'SMTP Server'],
                          'smtpPortLabel' : ['Порт' , 'Port'],
                          'attemptsToSendLabel' : ['Число попыток отправки почты', 'Maximum number of attempts to send'],
                          'authenticationLabel' : ['Аутентификация', 'Authentication'],
                          'isAuthenticateLabel' : ['Использовать аутентификацию на почтовом сервере', 'Authentication'],
                          'emailUserNameLabel' : ['Логин', 'User name'],
                          'emailPasswordLabel' : ['Пароль', 'Password'],
                          'useSslLabel' : ['Использовать безопасное SSL соединение', 'Use SSL secure connection'],
                          'sendbutton' : ['Применить', 'Apply'],
                          'testbutton' : ['Тест', 'Test'],
                          'settingsSavedMessage' : ['Настройки успешно сохранены!', 'Settings successfully saved!'],
                          
                          'manualhoursError' : ['Моменты создания отчетов заданы неверно!', 'Manual time points are set incorrectly!'],
                          'shopidError' : ['Имя магазина задано неверно!', 'Shop ID is set incorrectly!'],
                          'worktimefromError' : ['Время начала подсчета задано неверно!', 'The start time of counting is wrong!'],
                          'worktimetillError' : ['Время окончания подсчета задано неверно!', 'The end time of counting is wrong!'],
                          'intervalhoursError' : ['Частота создания отчетов указана неверно!', 'Report frequency is set incorrectly!'],
                          'emailtoError' : ['Получатель отчетов указан неверно!', 'Report recipient is set incorrectly!'],
                          'serveraddressError' : ['Адрес сервера отчетов указан неверно!', 'Report server address is set incorrectly!'],
                          'serverportError' : ['Порт сервера отчетов указан неверно!', 'Report server port is set incorrectly!'],
                          'sharepathError' : ['Сетевая папка указана неверно!', 'Shared folder is set incorrectly!'],
                          'shareuserError' : ['Пользователь сетевой папки указан неверно!', 'Shared folder user is set incorrectly!'],
                          'sharepasswordError' : ['Пароль сетевой папки указан неверно!', 'Shared folder password is set incorrectly!'],
                          'emailfromError' : ['Почтовый адрес для отправки указан неверно!', 'Email for reporting is set incorrectly!'],
                          'smtpserverError' : ['SMTP сервер указан неверно!', 'SMTP server is set incorrectly!'],
                          'smtpportError' : ['SMTP порт указан неверно!', 'SMTP port is set incorrectly!'],
                          'attemptstosendError' : ['Число попыток отправки почты указано неверно!', 'Attempts to send email are set incorrectly!'],
                          'smtpuserError' : ['Имя пользователя для отправки указано неверно!', 'Email username for reporting is set incorrectly!'],
                          'emailSentMessage' : ['Тестовое письмо успешно отправлено!', 'Test email successfully sent!'],
                          'pingSentMessage' : ['Тестовое сообщение успешно отправлено!', 'Test message successfully sent!'],
                          'shareMountMessage' : ['Тестовый файл успешно создан в сетевой папке!', 'Test file successfully created in shared filder!'],
                          },
              'channelsForm' : {
                          'title' : ['Каналы', 'Channels'],
                          'channelLabel' : ['Канал', 'Channels'],
                          'channelOption' : ['Канал 1', 'Channel 1'],
                          'isSwitchedLabel' : ['Обратить направление подсчета', 'Change counting direction'],
                          'saveVideoLabel' : ['Сохранять видео', 'Save video'],
                          'autocalibrationLabel' : ['Использовать автокалибрацию', 'Use autocalibration'],
                          'sendbutton' : ['Применить', 'Apply'],
                          'settingsSavedMessage' : ['Настройки успешно сохранены!', 'Settings successfully saved!'],
                          },
              'stasticForm' : {
                          'title' : ['Cтатистика', 'Statistics'],


              },
              'administrationForm' : {
                          'title' : ['Администрирование', 'Administration'],
                          'hostNameLabel' : ['Имя компьютера в сети', 'Host name'],
                          'sendbutton' : ['Применить', 'Apply'],
                          'datetimeLabel' : ['Дата и время', 'Date & Time'],
                          'logsLabel' : ['Отправить логи по почте', 'Send logs to email'],
                          'resenddataLabel' : ['Перепослать данные', 'Resend data'],
                          'allRadioLabel' : ['Все', 'All'],
                          'chooseDateRadioLabel' : ['Выбрать дату начала', 'Resend from'],
                          'notificationsLabel' : ['Настройка событий', 'Events settings'],
                          'notifyLabel' : ['Уведомлять о событиях камеры', 'Notify about camera events'],
                          'notifyEmailLabel' : ['Отправлять на адрес' , 'Email to send'],
                          'networkLabel' : ['Настройка сети', 'Network settings'],
                          'networkTypeLabel' : ['Тип сети', 'Network type'],
                          'wifiessidLabel' : ['Имя сети', 'Network name'],
                          'wifiPasswordLabel' : ['Пароль', 'Password'],
                          'ipCounfigurationLabel' : ['Конфигурация IP', 'IP configuration'],
                          'ipDynamicLabel' : ['Динамическая', 'Dynamic'],
                          'ipStaticLabel' : ['Статическая', 'Static'],
                          'ipAddressLabel' : ['IP адрес', 'IP address'],
                          'ipMaskLabel' : ['Маска подсети', 'Subnet mask'],
                          'gatewayLabel' : ['Шлюз', 'Gateway'],
                          'dnsServerLabel' : ['DNS сервер', 'DNS server'],
                          
                          'hostnameChangeMessage' : ['Сетевое имя было изменено.\n Счетчик будет перезагружен!', 'Hostname successfully changed.\n Restart is in progress!'],
                          'datetimeChangeMessage' : ['Время и дата были изменены!', 'Date and time successfully changed!'],
                          'logsSendMessage' : ['Логи будут отправлены на ваш email!', 'Logs will be sent to your email!'],
                          'dataSendMessage' : ['Данные будут повторно отправлены!', 'Data will be sent!'],
                          'settingsSavedMessage' : ['Настройки успешно сохранены!', 'Settings successfully saved!'],
                          
                          'hostnameError' : ['Имя компьютера в сети указано неверно!', 'Host name is set incorrectly!'],
                          'datetimefieldError' : ['Время и дата указаны неверно!', 'Date and time are set incorrectly!'],
                          'emailtoError' : ['Email адрес указан неверно!', 'Email address is set incorrectly!'],
                          'ipaddressError' : ['IP адрес указан неверно!', 'IP address is set incorrectly!'],
                          'ipmaskError' : ['Маска сети указана неверно!', 'Network mask is set incorrectly!'],
                          'gatewayError' : ['Шлюз указан неверно!', 'Gateway is set incorrectly!'],
                          'dnsserverError' : ['DNS сервер указан неверно!', 'DNS server is set incorrectly!'],
                          },
              'updateForm' : {
                          'title' : ['Обновление', 'Update'],
                          'updatePackageLabel' : ['Выберите пакет обновлений', 'Choose update package'],
                          'chooseFile' : ['Выбрать', 'Сhoose'],
                          'sendbutton' : ['Загрузить', 'Upload'],
                          'fileLoadMessage' : ['Файл был загружен. Идет обновление ПО!', 'File loaded. Update is in progress!'],
                          'chooseFileError' : ['Ошибка! Выберите файл!', 'Error! Choose file for update!'],
                          'incorrectFileError' : ['Ошибка! Выбран некорректный файл!', 'Error! incorrect file chosen!'],
                          'updateFinished' : ['Обновление успешно завершено!', 'Update successfully finished!'],
                          },
              'passwordForm' : {
                          'title' : ['Пароль', 'Password'],
                          'oldPasswordLabel' : ['Старый пароль', 'Old password'],
                          'newPasswordLabel' : ['Новый пароль' , 'New password'],
                          'newRepeatedPasswordLabel' : ['Подтверждение', 'Confirm password'],
                          'sendbutton' : ['Применить', 'Apply'],
                          'passwordChangedMessage' : ['Пароль был успешно изменен!', 'Password successfully changed!'],
                          'passwordNotEqual' : ['Ошибка! Новый пароль не совпадает с подтверждением!', 'Error! New password is not equal to repeated password!'],
                          'incorrectOldPassword' : ['Ошибка! Старый пароль указан неверно!', 'Error! Incorrect old password!'],
                          'incorrectNewPassword' : ['Ошибка! Новый пароль указан неверно!', 'Error! Incorrect new password!'],
                          'incorrectRepeatedPassword' : ['Ошибка! Подтверждение пароля указано неверно!', 'Error! Incorrect repeated password!'],
                          },
              
              }

TabDictionary = {
        'settingsTab' : ['Настройки', 'Settings'],
        'channelsTab' : ['Каналы', 'Channels'],
        'administrationTab' : ['Администрирование', 'Administration'],
        'updateTab' : ['Обновление', 'Update'],
        'passwordTab' : ['Пароль', 'Password'],
        'exitTab' : ['Выход', 'Exit'],
        'stasticTab' : ['Cтатистика', 'Statistics'],
                }

CommonDictioanry = {
        'formErrors' : ['Ошибки при вводе формы!', 'There are some form errors!'],
                }